language: java

before_install: 
    - sudo add-apt-repository -y "deb http://cz.archive.ubuntu.com/ubuntu raring main universe"
    - sudo apt-get update
    - sudo apt-get install build-essential libssl-dev libdb5.1++-dev libboost1.53-all-dev libqrencode-dev libminiupnpc-dev

install:
    - git clone https://github.com/gamers-coin/gamers-coinv3
    - cd gamers-coinv3/src/
    - make -f makefile.unix USE_UPNP=1 USE_IPV6=1 USE_QRCODE=1
    - mkdir /home/travis/.gamerscoin
    - echo "rpcuser=gamerscoinrpc" >> /home/travis/.gamerscoin/gamerscoin.conf
    - echo "rpcpassword=YOUR_STRONG_PASSWORD" >> /home/travis/.gamerscoin/gamerscoin.conf
    - cat /home/travis/.gamerscoin/gamerscoin.conf
    - nohup ./gamerscoind &

before_script:
    - echo "export GAMERS_COIN_RPC_USERNAME=gamerscoinrpc" >> /home/travis/.bash_profile
    - echo "export GAMERS_COIN_RPC_PASSWORD=YOUR_STRONG_PASSWORD" >> /home/travis/.bash_profile
    - cat /home/travis/.bash_profile
    - source /home/travis/.bash_profile
    - cd /home/travis/build/johngame/Gamersoin-JRPC

script: mvn test
